### ISSUE TITLE
NullPointerException in SqsMessageFetcher

### ISSUE THREAD

**Issue by Rafal-Laskowski** [thombergs/sqs-starter#6]
Hi!

What might be the cause of:
```
java.lang.NullPointerException: null
        at io.reflectoring.sqs.internal.SqsMessageFetcher.fetchMessages(SqsMessageFetcher.java:35) ~[sqs-starter-0.0.9.jar:na]
        at io.reflectoring.sqs.internal.SqsMessagePoller.pollMessages(SqsMessagePoller.java:59) ~[sqs-starter-0.0.9.jar:na]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```

In Java Spring Boot application?

Looks like `result` variable is null here.

```
List<Message> fetchMessages() {

    logger.debug("fetching messages from SQS queue {}", properties.getQueueUrl());

    ReceiveMessageRequest request = new ReceiveMessageRequest()
        .withMaxNumberOfMessages(properties.getBatchSize())
        .withQueueUrl(properties.getQueueUrl())
        .withWaitTimeSeconds((int) properties.getWaitTime().getSeconds());

    ReceiveMessageResult result = sqsClient.receiveMessage(request);

    if (result.getSdkHttpMetadata().getHttpStatusCode() != 200) {
      logger.error("got error response from SQS queue {}: {}",
          properties.getQueueUrl(),
          result.getSdkHttpMetadata());
      return Collections.emptyList();
    }

    logger.debug("polled {} messages from SQS queue {}",
        result.getMessages().size(),
        properties.getQueueUrl());

    return result.getMessages();
  }
```

**Comment by thombergs** [comment]
Hmm, I'd rather think that the result of `getSdkHttpMetadata()` is `null`, but I can't be sure.

Try out version 0.0.10, I have added a special handling for that case there. 0.0.10 should be available on Maven Central shortly (it's already available on bintray).
